# let the baudtime run as the only role of backend
tcp_port = "8088"
http_port = "80"
max_conn = 10000
namespace = "n1"
lookback_delta = "5s"

[limit]
  rlimit = 102400
  max_points_total = 3600000
  max_points_per_series = 6000
  inbound_kilo_bytes_per_sec = 0

[etcd]
  endpoints = ["localhost:2379"]
  dial_timeout = "5s"
  rw_timeout = "15s"
  retry_num = 2
  retry_interval = "2s"

[storage]
  [storage.tsdb]
    path = "/tmp/tsdb"
    retention_duration = "360h"
    block_ranges = [1800000, 3600000, 14400000, 28800000, 86400000]
    enable_wal = false
  [storage.stat_report]
    heartbeart_interval = "30s"
    session_expire_ttl = "30s"
  [storage.replication]
    sample_feed_conns_num = 16
    handleoff_size = "256m"
    heartbeart_interval = "30s"

[jaeger]
  sampler_type = "ratelimiting"
  sample_num_per_sec = 10000
  agent_host_port = ""
  collector_endpoint = "http://xx.xx.com/api/traces"
